@TodoApi_HostAddress = http://localhost:5198


### lists

GET {{TodoApi_HostAddress}}/api/lists

###

GET {{TodoApi_HostAddress}}/api/lists/1

###

POST {{TodoApi_HostAddress}}/api/lists
Content-Type: application/json

{
  "name": "Work ",
  "description": "things"
}

###

POST {{TodoApi_HostAddress}}/api/lists/archive/1

###

DELETE {{TodoApi_HostAddress}}/api/lists/1


### items

GET {{TodoApi_HostAddress}}/api/items/1

###

GET {{TodoApi_HostAddress}}/api/lists/1/items

###

GET {{TodoApi_HostAddress}}/api/lists/1/items?status=Completed

###

POST {{TodoApi_HostAddress}}/api/lists/1/items
Content-Type: application/json

{
  "title": "api",
  "notes": "test",
  "priority": "1",
  "due": "2026-07-10T17:00:00"
}

###

PUT {{TodoApi_HostAddress}}/api/items/1/status
Content-Type: application/json

{
  "status": "Completed"
}

###

POST {{TodoApi_HostAddress}}/api/items/1/complete

###

POST {{TodoApi_HostAddress}}/api/items/1/tags
Content-Type: application/json

{
  "tagIds": [1, 2]
}

###

DELETE {{TodoApi_HostAddress}}/api/items/1


### tags

GET {{TodoApi_HostAddress}}/api/tags

###

POST {{TodoApi_HostAddress}}/api/tags
Content-Type: application/json

{
  "name": "urgent"
}

###

POST {{TodoApi_HostAddress}}/api/tags/merge
Content-Type: application/json

{
  "sourceTagId": 2,
  "targetTagId": 1
}

###

DELETE {{TodoApi_HostAddress}}/api/tags/2